# Generated by Django 2.2 on 2022-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
