# Generated by Django 2.1.5 on 2022-07-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220718_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Uncategories', on_delete=django.db.models.deletion.CASCADE, to='event.Category'),
        ),
    ]
